#!/usr/bin/env python3
import serial
import random

if __name__ == '__main__':
    ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
    ser.reset_input_buffer()

    while True:
        #number = ser.read()
        #sending to arduino motor ON and OFF State
        motorSwitch = random.randint(0,1)
        print("Button has been pressed.")
        print("Sending number " + str(motorSwitch) + " to Arduino.")
        ser.write(str(motorSwitch).encode('utf-8'))

